# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Provisioning stage (A)
  jobs:
  - job: A1
    steps:
    - script:  echo Preparing the environment!
- stage: Build stage (B)
  jobs:
  - job: B1
    displayName: Initial job
    steps: 
    - script: echo Hello, world!
    - script: echo Something is fishy!
  - job: B2
    displayName: Second job
    steps:
    - script: echo Building the app!
- stage: Test stage (C)
  jobs:
  - job: A1
    steps:
    - script:  echo Testing the app!
- stage: Deploy stage (D)
  jobs:
  - job: A1
    steps:
    - script:  echo Deploying the app to production!
      
