# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: provisioning_stage_A
  jobs:
  - job: A1
    steps:
    - script:  echo Preparing the environment!
- stage: build_stage_B
  jobs:
  - job: B1
    displayName: initial_job
    steps: 
    - script: echo Hello, world!
    - script: echo Something is fishy!
  - job: B2
    displayName: second_job
    steps:
    - script: echo Building the app!
- stage: test_stage_C
  jobs:
  - job: A1
    steps:
    - script:  echo Testing the app!
- stage: deploy_stage_D
  jobs:
  - job: A1
    steps:
    - script:  echo Deploying the app to production!
      
